var viewtest = require('./view/view.test.js');  // by parsing this should be evaluated already...
var legendtest = require('./legend/legend.test.js');  // by parsing this should be evaluated already...
var d3mvctest = require('./d3mvc/d3mvc.test.js');
//var axisbrowsertest = require('./axis/axis.browsertest.js');
